# Generated by Django 5.1 on 2024-08-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demoapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="viedo",
            field=models.CharField(default="/static/default_video.mp4", max_length=255),
        ),
    ]
